language: node_js
node_js:
- 0.12.0
deploy:
  provider: npm
  email: simbo@simbo.de
  api_key: "${NPM_API_KEY}"
  on:
    tags: true
    repo: simbo/eslint-config-simbo
after_script:
- npm run cover
- npm run codeclimate
env:
  global:
  - secure: pPTGoRpPZjhD7xv8u1OWLWqbQrj7IB4tMxdvNOoK79isqLfJwsndgBVpEfX9Dw2ijlQ292Dk3gaytFFDOzxq9EauRayjixkkKCHC5rrkVkwf/pCf2BE490zusBNcnaGgTjobxbj4J0lyjcGvVYU+POJLvrMAWyFrQPtoOTmYIJW0Rmvy3NAYphexF2j0RnbX+LMIdOZrdElRS3Fl4rrmxr01tg3Ff4o5uqBaMyXbAsC14H9yynwgT7dD/9pL2Ksb929/bGPCaNJlHynJLTK/RveUcIgDiudS33D61nC1g2IC4/UqbTfgx8KnIBXl17Hr3cD+M+ZjeeuZ6LG390iB7RDAoq4qYqCy++vUTKUCpgWi6nrMgmcR8ZvwYpjr80ZVNznQxJrKTF3iO1AyDI0ABSTJ9WaX9aAFPsX0ZDkNRTcscWEz8ajtiP8U3jQaw9ShzbsEvQ1nrYxmDaYmO5XMLizBXvrCYliTy0xUHqbLl/rpHYfzNbcotR1ChvA/pzh2yMcbap3LHofrwLgptEMU7/5uFL/AHcsnIniZhN9lMBn7ptJZe63C6hj8PLA4eTaDAXfOUn3fxwNgfhVeEU9NaCE7152MOrZHEVS7WhbV5S/IwSCdizQApk00lKZOeA2y2KUw0vRoqfbT98PUBAEZCyOugmNP7LwmvDDxxaHANoA=
  - secure: lh3G2vEns5AvbpieGHwKS6l4TR2EindKbIzKFINJkMT7TL0HYoG2a1Y1/gVvHvK/NTn3KrnRwLovCK5u9mtljryBpf3dY4K9IAgyNLtnTedMFUXsJqBEk/2TjOCKiIHKq0cWja43LqGIigepLX5caYQrPOjCeF3BQ8dNaf5otlpY6BQZWde1RcqeCIMPfCuGw+8pG62DXXPB6zi7xVf4zINkECQHvPdSyTsDXhp/gFfyCzHTgUil13Xlo2NDDtXTKq9nTQeeQn0BKaQ0d429HJyEoGf5Ejjt+/aICPT8jBf168z70c+R+z+H39RhiroHNclThc/fGWpVlZvMW05NeoWW7Y38k2fqnHmoUKVHL8vaLX1/nJS2/iD+eSyHR4BQ3vbtvAKM0eMJnoPIceIB3qoQKuCHuViucRqyt+nQtaPJwULmV3GHKV2kl8/MyfLPAlxoZEuwqDF5fur2k29ksWlpG1IO1ejiLDTE3gtF/ejTniv6rIhdpBqKZY0ak1ywBypwmvcLUUi/ENAo5wf+NN2FnImOHbdQxiLHlrY5PGuYlLz5lMYz+/qKw4wFi75Ewywx2We8YodqiN48VPaB/QK+8XMCtyGB0wLE53mBtH9WImADfm8zDXFhPh4mRmMxcak6PLKaar0ULRVUATDS8X3dKGnrcuNbMp8oCJqSfmc=
